"""Initial Revision

Revision ID: 0e0024b069d6
Revises: 
Create Date: 2020-08-20 15:28:24.820807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0024b069d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('abbv', sa.String(length=4), nullable=False),
    sa.Column('rich', sa.Boolean(), nullable=True),
    sa.Column('stock_price', sa.Float(), nullable=True),
    sa.Column('price_diff', sa.Float(), nullable=True),
    sa.Column('months', sa.Integer(), nullable=True),
    sa.Column('increase_chance', sa.Integer(), nullable=True),
    sa.Column('max_increase', sa.Float(), nullable=True),
    sa.Column('max_decrease', sa.Float(), nullable=True),
    sa.Column('decay_rate', sa.Float(), nullable=True),
    sa.Column('bankrupt', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gain', sa.Integer(), nullable=True),
    sa.Column('lost', sa.Integer(), nullable=True),
    sa.Column('new', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shares',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'company_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shares')
    op.drop_table('user')
    op.drop_table('settings')
    op.drop_table('company')
    # ### end Alembic commands ###
