"""Added 3 more fields on user for leaderboard purposes

Revision ID: 0ed94c4186e8
Revises: caf4cb79379b
Create Date: 2022-08-02 09:17:45.958803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed94c4186e8'
down_revision = 'caf4cb79379b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_balance_checked', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_most_stocks_owned_checked', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_most_stocks_worth_checked', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_most_stocks_worth_checked')
        batch_op.drop_column('last_most_stocks_owned_checked')
        batch_op.drop_column('last_balance_checked')

    # ### end Alembic commands ###
