"""added local_points field to user

Revision ID: 74511ee22b79
Revises: dafdc74bb371
Create Date: 2022-08-03 00:33:09.259320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74511ee22b79'
down_revision = 'dafdc74bb371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('local_points')

    # ### end Alembic commands ###
