"""Removed decay_rate

Revision ID: c1dc420b67d4
Revises: 0e0024b069d6
Create Date: 2020-08-20 17:04:38.421078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1dc420b67d4'
down_revision = '0e0024b069d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('decay_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decay_rate', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
