"""Added last_income_checked on user

Revision ID: dafdc74bb371
Revises: 0ed94c4186e8
Create Date: 2022-08-02 21:46:21.225913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafdc74bb371'
down_revision = '0ed94c4186e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_income_checked', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_income_checked')

    # ### end Alembic commands ###
